### ISSUE TITLE
Problem with hats and texthats

### ISSUE THREAD

**Issue by CzekoladowyFTG** [Kamshak/Pointshop2#146] opened 2020-10-23 08:59 UTC
Hello,

I have problem with hats and texthats. I have problem with "Jumping" hats. I have server TTT and when i equip hats does not stick to the head.

**Comment by TheNickSkater** [comment] 2020-11-15 13:07
Same issue

**Comment by Kamshak** [comment] 2020-11-18 17:40
The hat rendering is not done by PS2 but by PAC, so there is nothing that can be fixed in the code here to fix the issue unfortunately. 

Some addons cause these issues, I remember this can be caused by a 3rd person view addon or similar. Try disabling some addons that do 3d2d rendering, 3rd person or similar, it might fix the issue for you.

**Closed by Kamshak** 2020-11-18 17:40 UTC

**Comment by TheNickSkater** [comment] 2020-11-19 07:02
I actually found that uTime was the issue. I found other threads stating it's because of a util.traceline thats used on the client. I removed that part from uTime and it works great now.

**Comment by Kamshak** [comment] 2020-11-19 08:07
Nice solution and thanks for sharing!
